### ISSUE TITLE
Loading a custom theme

### ISSUE THREAD

**Issue by jcyamo** [bobbypriambodo/nord-spacemacs#1]
I am a heavy spacemacs user and have recently discovered the nord color theme. I was disappointed to find out there is currently no official port, so I appreciate your effort in making one available!

I just wanted to mention another option for loading a custom theme. Here is how I do it:
- First create a private themes directory, and then save `nord-theme.el` there:
```sh
$ mkdir ~/.emacs.d/private/themes
```
- Now, add that directory as a custom theme path in your `dotspacemacs/user-init` function:
```elisp
(defun dotspacemacs/user-init ()
  ...
  (add-to-list 'custom-theme-load-path "~/.emacs.d/private/themes/"))
```
- Now you may simply add `nord` to the list of available themes:
```elisp
dotspacemacs-themes '(nord)
```

**Comment by bobbypriam** [comment]
Thanks for telling, @jonyamo! I've updated the Usage section of the readme to link to this issue. I too am yearning for an official port, and [it's definitely on the way](https://github.com/arcticicestudio/nord/issues/6). I'll be sure to deprecate this repo when one comes out.

I'm closing this issue 🙂
